### ISSUE TITLE
If you run this you will be banned

### ISSUE THREAD

**Issue by pwnedbytoxic** [call-042PE/Paranoid#5]
Interception is banned. I haven't been able to play valorant with my brother for a month despite using every spoofer available. Don't even think about using this.

**Comment by call-042PE** [comment]
![paster](https://image.noelshack.com/fichiers/2016/26/1467309320-risitas158.png)

**Comment by axxo1337** [comment]
You must be kidding

**Comment by DavraYoung** [comment]
Quick update, Interception driver gets disabled once you start the game(

**Comment by axxo1337** [comment]
Guys nobody cares it's open source code not your average p2c paste for script kiddes
